### ISSUE TITLE
Masterlist of TODO

### ISSUE THREAD

**Issue by karrui** [karrui/tetris-ai#1]
- [x] Heuristics (or should we call them features?)
  - [x] Minimize height increase - @karrui
  - [x] Minimize average height increase - @karrui 
  - [x] Minimize holes - @matilds 
  - [x] Maximise rows cleared? (This is probably a heuristic, then maximizing score will be the goal) - @karrui
  - [x] Minimise the absolute different between neighbours - ensure the top looks relatively flat - @chweeee 

- [ ] Training function(s)? - @pohjie 
  - [ ] Gradual descent?
  - [ ] Genetic Algo?
  - [ ] Simulated annealing?
  - [x] Particle swarm optimization

- [x] Scoring class for utility fx

- [x] Set up layout for report
